apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactions
  labels:
    app: githubactions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: githubactions
  template:
    metadata:
      labels:
        app: githubactions
    spec:
      containers:
        - name: primuslearning
          image: 290720700779.dkr.ecr.eu-west-1.amazonaws.com/githubactions:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080